zephyr_compile_definitions(
    -DSTD_GCC=1
	-DTLKAPI_USE_INTERNAL_SPECIAL_UART_TOOL=0
	-DSDK_RELEASE_CHECK_EN=1
	# -D__PROJECT_ACL_CONN_DEMO__=1
	-DAPP_FLASH_PROTECTION_ENABLE=1
	-DFIX_AUX_CONN_SLOT_IDX_CAL=1
	-DVCD_EN=0
	-DSCH_DEBUG_EN=0

	-DCHIP_TYPE=CHIP_TYPE_${SOC}
	-DBLC_ZEPHYR_BLE_INTEGRATION=1
	-DLL_FEATURE_SUPPORT_LE_DATA_LENGTH_EXTENSION=1
	-DBLUETOOTH_VER=BLUETOOTH_VER_6_2
	-DLL_FEATURE_SUPPORT_PRIVACY=1
	-DOPTIMIZE_RAM_FOR_MATTER=1
	-DLL_FEATURE_SUPPORT_LOCAL_RPA=0
	-DLL_FEATURE_SUPPORT_PHY_TEST_MODE=0
	-DLL_FEATURE_SUPPORT_EXTENDED_SCANNER_FILTER_POLICIES=0
	-DLL_FEATURE_SUPPORT_LE_2M_PHY=1
	-DLL_FEATURE_SUPPORT_LE_CODED_PHY=0
	-DLL_FEATURE_SUPPORT_LE_EXTENDED_ADVERTISING=0
	-DLL_FEATURE_SUPPORT_LE_PERIODIC_ADVERTISING=0
	-DLL_FEATURE_SUPPORT_CHANNEL_SELECTION_ALGORITHM2=1
	-DLL_FEATURE_SUPPORT_MIN_USED_OF_USED_CHANNELS=0
	-DLL_FEATURE_SUPPORT_LE_EXTENDED_SCANNING=0
	-DLL_FEATURE_SUPPORT_LE_PERIODIC_ADVERTISING_SYNC=0
	-DLL_FEATURE_SUPPORT_SYNCHRONIZED_RECEIVER=0
	-DTIFS_VARIATION_WORKAROUND_MLP_CODE_IN_RAM=0
	-DLL_FEATURE_SUPPORT_LE_PING=0
	-DLL_FEATURE_SUPPORT_LE_PAST_SENDER=0
	-DLL_FEATURE_SUPPORT_LE_PAST_RECIPIENT=0
	-DLE_AUTHENTICATED_PAYLOAD_TIMEOUT_SUPPORT_EN=0
	-DDEBUG_GPIO_ENABLE=0
	-DSCH_TASK_PRIORITY_IN_CB_EN=0
	-DSTACK_IRQ_CODE_IN_SRAM_DUE_TO_FLASH_OPERATION=0
	-DSTACK_IRQ_CODE_IN_SRAM_DUE_TO_FLASH_OPERATION_V2=0
	-DBLC_PM_RETENTION_DRIVERS_ONLY=1
	-DRF_RX_DCOC_SOFTWARE_CAL_EN=1
	-DLL_FEATURE_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER=0
	-DLL_FEATURE_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER=0
	-DLL_FEATURE_SUPPORT_ADVERTISING_CODING_SELECTION=0
	-DCUSTOM_DARWIN_FMN_ENABLE=0

	#todo: hci should be enabled after test
	-DLL_FEATURE_ENABLE_CONNECTION_PARA_REQUEST_PROCEDURE=0
	#used for short connection application, for example, 7.5ms keyboard/mouse
	-DBLC_ZEPHYR_BLE_INTEGRATION_SHORT_CONNECTION_APPLICATION=0

	# temporary solution
	-DTLK_SCH_ACCESS_CODE_TASK_DISABLE=1
)

if(CONFIG_BT_CENTRAL)
	zephyr_compile_definitions(
		-DCONTROLLER_GEN_P256KEY_ENABLE=1
		-DCONN_MAX_NUM_CONFIG=CONN_MAX_NUM_C1_P1
		-DLL_FEATURE_SUPPORT_LE_ENCRYPTION=1
		-DLL_FEATURE_SUPPORT_LE_LEGACY_SCANNING=1
		-DLL_FEATURE_SUPPORT_LE_EXTENDED_INITIATE=1
	)
else()
	zephyr_compile_definitions(
		-DCONTROLLER_GEN_P256KEY_ENABLE=0
		-DCONN_MAX_NUM_CONFIG=CONN_MAX_NUM_C0_P1
		-DLL_FEATURE_SUPPORT_LE_ENCRYPTION=1
		-DLL_FEATURE_SUPPORT_LE_LEGACY_SCANNING=0
		-DLL_FEATURE_SUPPORT_LE_EXTENDED_INITIATE=0
	)
endif()

if(CONFIG_PM)
	if(CONFIG_SOC_SERIES_RISCV_TELINK_TLX_RETENTION)
		zephyr_compile_definitions(
			-DBLMS_PM_ENABLE=1
			-DBLC_PM_EN=1
			-DMAILBOX_PM_VALUE_SYNC=1
			-DBLC_PM_DEEP_RETENTION_MODE_EN=1
		)
	else()
		zephyr_compile_definitions(
			-DBLMS_PM_ENABLE=1
			-DBLC_PM_EN=1
			-DMAILBOX_PM_VALUE_SYNC=1
			-DBLC_PM_DEEP_RETENTION_MODE_EN=0
		)
	endif()
else()
	zephyr_compile_definitions(
		-DBLMS_PM_ENABLE=0
		-DBLC_PM_EN=0
		-DMAILBOX_PM_VALUE_SYNC=0
		-DBLC_PM_DEEP_RETENTION_MODE_EN=0
	)
endif()

if(CONFIG_TELINK_TL322X_ENABLE_N22)
	zephyr_compile_options(
			-DTLK_ONLY_BLE_HOST=1
			-DTLK_MAILBOX_MESSAGE_HOST_EN=1
			-DDUAL_CORE_MODE_ENABLED=1
	)
endif()

if(CONFIG_TELINK_TL322X_ENABLE_N22 AND CONFIG_PM)
	zephyr_compile_definitions(
		-DBLE_APP_PM_ENABLE=1
	)
endif()

if(CONFIG_BT_TLX_CHANNEL_SOUNDING)
	# Enable private control PDU for CS procedure update (matching cs_reflector_demo)
	zephyr_compile_definitions(
		-DLL_FEATURE_ENABLE_PRIVATE_CONTROL_PDU=1
		-DCS_SUPPORT_PRIVATE_CONTROL_PDU=1
	)

	zephyr_compile_definitions(
		-DHARDWARE_CHANNEL_SOUNDING_SUPPORT_EN=1
		-DLL_FEATURE_ENABLE_CHANNEL_SOUNDING=1
		-DLL_FEATURE_ENABLE_CHANNEL_SOUNDING_REFLECTOR=1
	)
else()
	zephyr_compile_definitions(
		-DHARDWARE_CHANNEL_SOUNDING_SUPPORT_EN=0
	)
endif()

zephyr_library_compile_options(
	-O2
	-flto=auto
	-ffat-lto-objects
	-fmessage-length=0
	-ffunction-sections
	-fdata-sections
	-mno-relax
	-fno-builtin
	-fomit-frame-pointer
	-fno-strict-aliasing
	-fshort-wchar
	-fuse-ld=bfd
	-fno-jump-tables
	# -Wno-address-of-packed-member
	# -Wall
	# -Wextra
	# -Wshadow
	# -Wimplicit-fallthrough
	# -Wpointer-arith
	# -Wredundant-decls
	# -Wcast-qual
	# -Wsign-compare
	# -Wunused-parameter
	# -Wunused-variable
	# -Wswitch
	# -Wstrict-prototypes
	# -Wmissing-field-initializers
	# -Wdeprecated-declarations
	# -Wenum-conversion
	# -Wpacked-not-aligned
	# -Wundef
)
